pentaho-bi.base-url=https://bi.sep.es.gov.br
pentaho-bi.user-id=${PENTAHO_BI_USER_ID:${pentahoBI.userId:}}
pentaho-bi.password=${PENTAHO_BI_PASSWORD:${pentahoBI.password:}}

pentaho-bi.procurement-years-path=/public/dashboard/pmo/dados_abertos/dados_abertos_lic_ano.cda
pentaho-bi.procurement-years-data-access-id=dados_abertos_lic_ano
pentaho-bi.procurement-organizations-path=/public/dashboard/pmo/dados_abertos/dados_abertos_lic_orgao.cda
pentaho-bi.procurement-organizations-data-access-id=dados_abertos_lic_orgao
pentaho-bi.procurement-processes-path=/public/dashboard/pmo/dados_abertos/dados_abertos_lic_processos.cda
pentaho-bi.procurement-processes-data-access-id=dados_abertos_lic_processos
pentaho-bi.procurement-detail-path=/public/dashboard/pmo/dados_abertos/dados_abertos_lic_licitacao.cda
pentaho-bi.procurement-detail-data-access-id=dados_abertos_lic_licitacao
